export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const GET_AUTH_USER = "GET_AUTH_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOAD_USER = "LOAD_USER";
export const GOOGLE_LOGIN = "GOOGLE_LOGIN"

export const EDIT_USER_DETAILS = "EDIT_USER_DETAILS"
export const CLEAR_ALERT = "CLEAR_ALERT"
export const REGISTER_ERROR = "REGISTER_ERROR"
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"
export const LOAD_USER_ERROR = "LOAD_USER_ERROR"
export const GOOGLE_LOGIN_ERROR = "GOOGLE_LOGIN_ERROR"
export const EDIT_USER_DETAILS_ERROR = "EDIT_USER_DETAILS_ERROR"


export const ADD_AVATAR = "ADD_AVATAR";
export const REMOVE_AVATAR = "REMOVE_AVATAR";

export const ADD_AVATAR_ERROR = "ADD_AVATAR_ERROR"
export const RENOVE_AVATAR_ERROR = "REMOVE_AVATAR_ERROR"

export const ADD_PROFILE_BIO = "ADD_PROFILE_BIO";
export const EDIT_PROFILE_BIO = "EDIT_PROFILE_BIO";

export const ADD_PROFILE_BIO_ERROR = "ADD_PROFILE_BIO_ERROR"
export const EDIT_PROFILE_BIO_ERROR = "EDIT_PROFILE_BIO_ERROR"

export const LOADING = "LOADING"

